### ISSUE TITLE
Create `round_coordinates()` function to fuzzy coordinates before publication

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#147]
`round_coordinates(package, decimals = 3)`

- [x] `decimals`: only valid/useful values are: 1, 2, 3 (4 is an uncertainty of 16m which doesn't help fuzzying)
- [x] function rounds latitude/longitude to set decimals
- [x] function adds respectively 15691, 1570, 157 coordinate uncertainty to already present uncertainty
- [x] If the existing uncertainty is NULL, the function assumes 30 as starting uncertainty
- [x] set the `coordinatePrecision` in the metadata
- [x] function assesses the current coordinatePrecision:
  - if higher (e.g. already 3, but user wants 2): substract 157, add 1570
  - if lower (e.g. already 2, but user wants 3): error, can't round

**Comment by tucotuco** [comment]
For the assessment of current precision, don't forget the case of original data with detected reduced coordinate precision and without uncertainty. You'll have to construct that uncertainty from scratch without any subtractions.

**Comment by peterdesmet** [comment]
To assess from scratch, should I take the most occurring number of decimals in the data or the maximum number of decimals?

**Comment by tucotuco** [comment]
IF you are sure the original data are in decimal degrees and IF the measure of original coordinate precision is at the data set level rather than per record, I would recommend to use the furthest right non-zero digit for both decimalLatitude and decimalLongitude. You could also do this at the record level if there is reason to believe that a data set might consist of record of varying precision. 
IF there is any chance that the original records could be in other coordinate formats (DMS, degrees decimal minutes), then you should try to detect those too and adjust the coordinate uncertainty accordingly. Code for detecting coordinatePrecision can be found [here](https://github.com/tucotuco/biogeomancer-core/blob/06c96cd0e58a23ad1f88f7411e07c90c58841f0f/core/src/org/biogeomancer/utils/Coordinate.java#L143).

If you need code for calculating uncertainty knowing coordinate precision, by latitude, you can find that [here](https://github.com/VertNet/georefcalculator/blob/1cc9f4c78fa9188800c9c93c0003cd63db295c74/support.js#L1931) or [here](https://github.com/GeomancerProject/Software/blob/6fcb1fbab9050c5d0ad6f3730295bbee0b618704/geomancer/point.py#L122).

**Comment by peterdesmet** [comment]
Function implemented at #148.

`coordinatePrecision` in the metadata is used first:
- Will prevent user from rounding from e.g. 2 to 3
- Function will not overestimate uncertainty on multiple runs of the function (substracts uncertainty associated with original precision before adding new uncertainty)

When `coordinatePrecision` is undefined, the function makes a guess based on the data. This check is simple: it checks the maximum number of decimals it can find in the longitude column over the whole dataset. Note: better would be furthest **non-zero** digit for latitude **and longitude**.

- Will still prevent user from rounding from e.g. 2 to 3
- On the first run of the function `coordinatePrecision` will be set, so that the first approach is used the second time

Edge case:

1. one record has 7 digits, all the rest has 2
2. user wants to round to 3, this is possible because 3 < 7
3. data will be rounded to 3, but most data will remain having 2 decimals (except the 1 record)
4. `coordinateUncertainty` will be:
  - when `coordinateUncertainty` was undefined: 30 + 157, which is likely an underestimate given the 2 decimals
  - when `coordinateUncertainty` was defined: original value + 157, which might be an overestimate
6. `coordinatePrecision` will be set to 0.001

I'm fine with those downsides, since we can indicate to users to set the `coordinatePrecision` in the metadata to better document the precision of their coordinates.

**Comment by peterdesmet** [comment]
Implemented in #148.
