### ISSUE TITLE
Have `read_wi()` assign title

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#158]
Otherwise, with `write_eml()`, `title` does not exist in package. Can we create it in `read_wi()`, or is it ok to request it only when writing eml?

_Originally posted by @Rafnuss in https://github.com/inbo/camtraptor/issues/156#issuecomment-1238869817_

**Comment by peterdesmet** [comment]
`read_wi()` does indeed not assign a dataset title. We could assign the project title as dataset title, but I don't know we should consider it the same thing. What do you think?

> European Wildcat Project (2017-2019)

Note that `write_eml()` allows to set a title at that point. It can also be assigned by `package$title <- "My title"`. Did you consider it a good thing to have to specify a title yourself?

**Comment by Rafnuss** [comment]
Yes, I saw that you can specify it manually, so that might be the best solution.
But I was trying to figure out what was the difference between `package$title` and `package$name`. I cannot find title in the metadata documentation (https://tdwg.github.io/camtrap-dp/metadata/). Maybe it would be good to add it there and explain the difference with name (eg. link to https://specs.frictionlessdata.io/data-package/#name and https://specs.frictionlessdata.io/data-package/#title)? 

And I also think that a description on the difference between `package$title` and `package$project$title` would be helpful for novice like me. Is this actually similar to GBIF project (https://ipt.gbif.org/manual/en/ipt/2.5/gbif-metadata-profile#project)?

**Comment by peterdesmet** [comment]
Indeed, project is similar to the project in EML. I'll make an issue at Camtrap DP to document package$title
