### ISSUE TITLE
afstemmen & integreren functies van package Henjo in camtraptor

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtraptor#202]
Henjo (who is a collaborator of Patrick Jansen at WUR has created a package with some functions for data exploration of agouti data in camtrap-DP format.

To do:
- have a look at the package: https://wec.wur.nl/r/ctdp/ and https://git.wur.nl/camtrap/ctdp/
- see which functions are overlapping with existing camtraptor functions
- list non-overlapping functions that would be interesting to integrate into the next version of camtraptor in collaboration with Henjo
- prioritize the functions to build

**Comment by damianooldoni** [comment]
Thanks @jimcasaer to contact us about this. Indeed, I think it's important indeed to not reinvent the wheel and to join our efforts to build something together where possible. I will set a doodle for the second half of April.

**Comment by damianooldoni** [comment]
Doodle set up. Henjo, Patrick and you all are invited to fill it in.

**Comment by peterdesmet** [comment]
Conclusions from the call

1. ctdp was developed so students could more easily analyse data exported from Agouti. It is not intended as a replacement for camtraptor, but does contain a number of very useful functions that might be beneficial to a wider audience. The [source code](https://git.wur.nl/camtrap/ctdp/) is public.
2. ctdp has an interesting data model that splits the data in more logical items. Especially the sequence allows to not have to join over media all the time. Joins are made every time a function is called.
3. It is not a good idea to have a massive df consisting of a join between all tables, because filtering on e.g. `scientific name = Vulpes vulpes`) will then remove absence data (i.e. deployments where Vulpes vulpes was not seen). Such a filter should work on observations only (keeping all deployments).
4. ctdp already implements separate filter functions (cf. #92). Rather than a generic `filter()` function it is better to make dedicated `filter_species()`, `filter_location()` functions. People can still rely on `dplyr::filter()` on a joined df if they want to.
5. It is better to retrieve data via functions, rather than `data$df`. It gives us more control when things change.
6. camtraptor's `read_camtrap_dp()` should do all the heavy lifting regarding understanding different versions of camtrap-dp and converting it to a data object that can be used by other functions, including ctdp functions.

**Comment by PietrH** [comment]
What is the status of this issue?

**Comment by damianooldoni** [comment]
Thanks @PietrH to ping about this. 
This issue can be closed. We are translating some of the conclusions in functions (or there are ad hoc issues tackling some specific aspects). We will make new issues if needed.
