### ISSUE TITLE
New function request: changes to 'get_custom_effort' 

### ISSUE THREAD

**Issue by MartijnUH** [inbo/camtraptor#333]
@damianooldoni following our meeting of 09/09/'24, @jimcasaer and I suggest the following changes to the `get_custom_effort` function:

inputs: no changes required

outputs:
- [ ] return the effort per group: one of `"day", "week", "month", "year"` and per `deploymentID`
- [ ] add a column `deploymentID` to the output data.frame
- [ ] add a column `locationName` to the output data.frame

This allows users to seamlessly calculate the total effort over all deployments (current default behaviour), effort per location or effort per deployment. (We could also add a new input parameter `level` that is one of: `"overall", "location", "deployment"` that acts as a switch between the desired output -- total effort - effort per location - effort per deployment. Then users do not have to calculate this themselves).

**Comment by MartijnUH** [comment]
I worked out an example of the function (extract the R-script in the zip-file and run locally): [get_custom_effort2.zip](https://github.com/user-attachments/files/16946310/get_custom_effort2.zip)

**Comment by damianooldoni** [comment]
This issue is strictly linked to existent one: https://github.com/inbo/camtraptor/issues/280. More or less same conclusions.
I will implement this soon and so updating to camtraptor 0.26.0. 

Notice that I will think more about the future of `get_effort()` and `get_custom_effort()` (see #236) while working on camtraptor 1.0.0.
