### ISSUE TITLE
Add `CITATION.cff`

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#345]

**Comment by damianooldoni** [comment]
Implemented in version 1.0

**Comment by wolfmissotten** [comment]
@damianooldoni I think you should execute `cffr::cff_write()` again before making the release of version 1.0.0 as the `DESCRIPTION` file has changed since december 2024. All years mentioned in `CITATION.cff` are still 2024 and will be automatically updated to 2026. Also there are new packages in 'imports' of the `DESCRIPTION` file since 2024.

**Comment by damianooldoni** [comment]
Good point, @wolfmissotten! I reopen the issue editing the title ("update" instead of "add"). I think we can do it now in the "vignette" branch. If you have time, you can give it a try. Let me know in this issue.

**Comment by wolfmissotten** [comment]
I reverted my last commit because the CITATION.cff is build on DESCRIPTON and mentions a release date. I think it's better to wait for the DESCRIPTION file to be final, as [we are not sure yet](https://github.com/inbo/camtraptor/commit/c43cd842b649cc9a8b5dff950ff93f4a81b358f9) about the `Date` in the DESCRIPTION.

**Comment by wolfmissotten** [comment]
I close this issue as updating `CITATION.cff` is part of the checklist in issue #309, so this issue is redundant.
